### ISSUE TITLE
setting properties to undefined in declassify

### ISSUE THREAD

**Issue by nopbyte** [SEDARI/UPFROnt#1]
When objects are declassified in the new version, it seems they are being set to undefined. 
This may an issue when hasOwnProperty is used since it would return true :(

http://stackoverflow.com/questions/14967535/delete-a-x-vs-a-x-undefined

**Comment by dschrecking** [comment]
Latest version will, by default, remove the property completely from the declassified object. Actions specified in the reading policies may influence this behavior by not returning null but, e.g., a randomized string, a fuzzied location, etc.
